# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project information
site_name: LTY's Homepage
site_url: https://mydomain.org/mysite
site_author: Liu Tianyang

# Repository
repo_name: Pokonliu/HomePage
repo_url: https://github.com/Pokonliu/HomePage

# Copyright
copyright: Copyright &copy; 1995 - 2024 LTY

# Configuration
theme:
  language: zh

  name: material
  
  favicon: assets/favicon.ico

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    logo: simple/alienware

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  features:
    - announce.dismiss

    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    
    # - header.autohide
    
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.path


    - search.highlight
    - search.share
    - search.suggest
    
    - toc.follow
    # - toc.integrate

nav:
  - HOME: index.md
  - LCMS: LCMS/index.md
  - VIE: VIE/index.md
  - RK3588: RK3588/index.md
  - AI: AI/index.md
  - BLOG: blog/index.md

plugins:
  - search
  - blog

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<302702801@qq.com>
    - icon: fontawesome/brands/weixin
      link: mailto:<koopdown>

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
