# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: My Docs
site_url: https://mydomain.org/mysite
theme:
  language: zh

  name: material
  
  favicon: assets/favicon.ico

  icon:
    logo: simple/alienware

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

  features:
    - navigation.footer
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.path

plugins:
  - search
  - blog

copyright: Copyright &copy; 1995 - 2024 LTY

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<302702801@qq.com>
    - icon: fontawesome/brands/weixin
      link: mailto:<koopdown>

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
